/**
 * Question Database Update Script
 * 
 * This script updates the database with AI-generated answers and explanations
 * for a set of test questions. It takes the results of the OpenAI test run
 * and updates the corresponding QuestionBag documents in MongoDB.
 * 
 * The script is designed to:
 * 1. Connect to the MongoDB database
 * 2. Update each question with its AI-generated answer, explanation, and difficulty rating
 * 3. Track success and failure counts
 * 4. Provide a summary of the update process
 */

import mongoose from 'mongoose';
import { QuestionBag } from '../models/QuestionBag';
import dotenv from 'dotenv';

dotenv.config();

/**
 * Array of test results from the OpenAI API test
 * Each result contains:
 * - id: MongoDB document ID
 * - type: Question type (Critical Reasoning, Multiple Choice, etc.)
 * - aiAnswer: The answer letter (A-E) generated by the AI
 * - aiExplanation: The explanation for the answer provided by the AI
 * - difficulty: The difficulty rating (1-10) assigned by the AI
 */
const testResults = [
  {
    id: "6805aeac3c24674e653a1d3c",
    type: "Critical Reasoning",
    aiAnswer: "C",
    aiExplanation: "Option C undermines the argument by indicating that the fullerenes could have formed from the carbon in the shungite, not necessarily due to distinctive conditions of temperature and pressure, which is the premise of the original argument. The other options do not strongly challenge the argument's premise.",
    difficulty: 7.0
  },
  {
    id: "6805c4e077d692898d947d7c",
    type: "Multiple Choice",
    aiAnswer: "E",
    aiExplanation: "Option E seriously undermines the argument, as it implies that the conditions needed for shungite formation can't necessarily be generalized to Earth's crust. Other options don't detract from the opportunity to learn about the Earth's crust via fullerenes.",
    difficulty: 7.5
  },
  {
    id: "6805c4e077d692898d947d7d",
    type: "Multiple Choice",
    aiAnswer: "C",
    aiExplanation: "Option C undermines the economist's conclusion by introducing a hidden cost (long-term pain medication) not included in the $11,000 average. This could potentially make the $12,500 program more cost-effective. The other options do not directly address the cost comparison of the treatments, hence, they do not undermine the conclusion.",
    difficulty: 7.0
  },
  {
    id: "6805c4e077d692898d947d7e",
    type: "Multiple Choice",
    aiAnswer: "E",
    aiExplanation: "The activity of snakes, a major predator of young voles, from spring through early autumn, would lead to a higher mortality among young voles during those seasons. This supports the claim that the seasonal variation in group size is due to a seasonal variation in mortality rates. The other options do not directly relate to the mortality rate of young voles.",
    difficulty: 5
  },
  {
    id: "6805c4e077d692898d947d7f",
    type: "Multiple Choice",
    aiAnswer: "E",
    aiExplanation: "Option E provides the best explanation for why offspring of dolphins feeding at the beach have a lower life expectancy. By spending less time teaching their offspring how to catch fish in the wild, these offspring may be less equipped to survive on their own. The other options do not directly address the difference in life expectancy between the two groups of offspring.",
    difficulty: 7.5
  },
  {
    id: "6805c4e077d692898d947d80",
    type: "Multiple Choice",
    aiAnswer: "D",
    aiExplanation: "Option D adds a new dimension to consider. If the tiger sharks are killed, their prey (smaller sharks) might increase in number and deplete the fish population, negatively affecting the island's fishing industry. Other options address implications that are secondary to the economy or not directly related to the problem.",
    difficulty: 6.5
  },
  {
    id: "6805c4e077d692898d947d81",
    type: "Multiple Choice",
    aiAnswer: "E",
    aiExplanation: "E is correct because it states that Ertland apple distributors could afford to match Kosolian apple prices, neutralizing their competitive price advantage. A, B, C, and D are incorrect because they don't challenge the viability of Kosolia's plan directly.",
    difficulty: 7.5
  },
  {
    id: "6805c4e077d692898d947d82",
    type: "Multiple Choice",
    aiAnswer: "B",
    aiExplanation: "Option B most strongly supports the consultants' proposal as it clarifies that moving the station's entrance would not decrease the frequency of train usage among commuters. This is important because decreased usage could negatively impact the train company's revenue. Other options do not directly relate to the financial viability of the proposed renovations.",
    difficulty: 7.0
  },
  {
    id: "6805c4e077d692898d947d83",
    type: "Multiple Choice",
    aiAnswer: "C",
    aiExplanation: "Option C weakens the argument of the PZ 1000's overall safety by providing information that even though the PZ 1000 has the fewest injuries per accident, the cars in its class are more likely to be involved in accidents.",
    difficulty: 5
  },
  {
    id: "6805c4e077d692898d947d84",
    type: "Multiple Choice",
    aiAnswer: "B",
    aiExplanation: "Option B indicates the most serious weakness in the plan. If burning seaweed releases the same amount of CO2 as it absorbed, there would be no net reduction in atmospheric CO2. All other options either don't affect the efficacy of the CO2 reduction or discuss irrelevant financial or social aspects.",
    difficulty: 8.0
  },
  {
    id: "6805c4e077d692898d947d85",
    type: "Multiple Choice",
    aiAnswer: "E",
    aiExplanation: "Option E establishes an alternative route for the circulation of videos, which weakens Brad's objection that Videorama's sale couldn't account for the 10,000 rental decrease. The other options don't address the numerical discrepancy posed by Brad.",
    difficulty: 7
  },
  {
    id: "6805c4e077d692898d947d86",
    type: "Multiple Choice",
    aiAnswer: "D",
    aiExplanation: "Option D is correct because it suggests that customers often buy wine based on a general impression, which means they might not notice specific features like the color of the label. This undermines Danville's argument that the gold label makes their bottles distinguishable from Mourdet's. The other options are irrelevant or don't specifically undermine Danville's argument.",
    difficulty: 6
  },
  {
    id: "6805c4e077d692898d947d87",
    type: "Multiple Choice",
    aiAnswer: "E",
    aiExplanation: "Answer E is correct because it implies that many people who placed orders were not subscribers to Systems magazine. This resolves the potential conflict between the two findings, as the first refers only to subscriber behavior and the second to behavior of all people who placed orders. The rest of the options are irrelevant or don't help in resolving the conflict.",
    difficulty: 8.0
  },
  {
    id: "6805c4e077d692898d947d88",
    type: "Multiple Choice",
    aiAnswer: "C",
    aiExplanation: "The correct answer is C because it suggests that US manufacturers would have a competitive advantage in the US market, similar to European manufacturers in Europe. Options A, B, D, and E are irrelevant to the argument and do not logically complete the sentence.",
    difficulty: 7
  },
  {
    id: "6805c4e077d692898d947d89",
    type: "Multiple Choice",
    aiAnswer: "E",
    aiExplanation: "The argument assumes that smoking doesn't interfere with the effectiveness of vitamins and minerals. If smoking prevents these nutrients from helping, then increasing intake of such nutrients wouldn't necessarily improve lung function. The other options are either not making relevant assumptions or making assumptions that can be reasonably considered as false or unproven based on the information given.",
    difficulty: 7.5
  },
  {
    id: "6805c4e077d692898d947d8a",
    type: "Multiple Choice",
    aiAnswer: "A",
    aiExplanation: "The first boldface portion describes a situation while the second portion provides an explanation for it. Options B, C, D and E all incorrectly describe the first part as acknowledging a consideration against the argument or providing/supporting evidence for the argument.",
    difficulty: 7.5
  },
  {
    id: "6805c4e077d692898d947d8b",
    type: "Multiple Choice",
    aiAnswer: "C",
    aiExplanation: "The most useful factor to determine in evaluating the argument is whether there are any technological advances that could reduce the cost of extracting uranium from seawater (option C). This is because the argument's crux is cost-effectiveness, not scarcity or location of uranium or the comparison of seawater with freshwater.",
    difficulty: 5
  },
  {
    id: "6805c4e077d692898d947d8c",
    type: "Multiple Choice",
    aiAnswer: "D",
    aiExplanation: "This question asks what factors could have affected the experiment's outcome besides sulfur dioxide. Option D is correct because grime on greenhouse windows can block sunlight, affecting plant growth. The other options do not explain why plants in urban greenhouses might grow more slowly once sulfur dioxide is removed.",
    difficulty: 7.5
  },
  {
    id: "6805c4e077d692898d947d8d",
    type: "Multiple Choice",
    aiAnswer: "E",
    aiExplanation: "Option E directly explains why the accident rate increased: after the markings were painted, more drivers who had previously avoided these roads because of their danger now felt confident enough to use them, thereby increasing the chance of accidents. Other options do not offer a clear link between painting edge markings and the increase in accidents.",
    difficulty: 7
  },
  {
    id: "6805c4e077d692898d947d8e",
    type: "Multiple Choice",
    aiAnswer: "B",
    aiExplanation: "The argument assumes that importing grain or meat would not financially strain Gortlanders' incomes, which is stated in option B. Options A, C, D, and E are irrelevant as they don't directly affect the argument's conclusion about importing grain or meat.",
    difficulty: 7.5
  }
];

/**
 * Main function to update the database with AI-generated answers
 * 
 * The function:
 * 1. Connects to MongoDB
 * 2. Iterates through each test result
 * 3. Updates the corresponding question in the database
 * 4. Tracks success and failure statistics
 * 5. Provides a summary of the update operation
 */
const updateTestedQuestions = async (): Promise<void> => {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/gmat-quiz');
    console.log('Connected to MongoDB');
    
    // Update each question with AI-generated answers and explanations
    let successCount = 0;
    let errorCount = 0;
    
    for (const result of testResults) {
      try {
        // Convert string ID to ObjectId if needed
        const questionId = result.id;
        
        // Update the question in the database
        const updateResult = await QuestionBag.updateOne(
          { _id: questionId },
          { 
            $set: {
              AI_generated_correct_answer: result.aiAnswer,
              AI_generated_explanation: result.aiExplanation,
              questionDifficulty: result.difficulty
            }
          }
        );
        
        if (updateResult.modifiedCount > 0) {
          console.log(`Updated question ID: ${questionId} with AI answer: ${result.aiAnswer}`);
          successCount++;
        } else {
          console.log(`No changes made to question ID: ${questionId}`);
        }
      } catch (error) {
        console.error(`Error updating question ID: ${result.id}`, error);
        errorCount++;
      }
    }
    
    // Summary
    console.log('\n=== Update Summary ===');
    console.log(`Total questions: ${testResults.length}`);
    console.log(`Successfully updated: ${successCount}`);
    console.log(`Failed updates: ${errorCount}`);
    
    // Disconnect from MongoDB
    await mongoose.disconnect();
    console.log('Disconnected from MongoDB');
    
  } catch (error) {
    console.error('Error in update process:', error);
  }
};

// Run the script
updateTestedQuestions()
  .then(() => console.log('Update complete'))
  .catch(err => console.error('Script failed:', err)); 